import Vue from "vue";
import { Button } from "vant";
import { Tabbar, TabbarItem } from "vant";
import { Swipe, SwipeItem } from "vant";
import { Lazyload } from "vant";
import { Grid, GridItem } from "vant";
// import { Image } from 'vant';
import { Image as VanImage } from "vant";
import { Tab, Tabs } from 'vant';
import { Card } from 'vant';
import { Sidebar, SidebarItem } from 'vant';
import { List } from 'vant';
import { PullRefresh } from 'vant';
import { GoodsAction, GoodsActionIcon, GoodsActionButton } from 'vant';
import { Toast } from 'vant';
import { Checkbox, CheckboxGroup } from 'vant';
import { SubmitBar } from 'vant';
import { Stepper } from 'vant';
import { Form } from 'vant';
import { Field } from 'vant';
// import { Sku } from 'vant';
// import { Overlay } from 'vant';
import { Popup } from 'vant';
import { Cell, CellGroup } from 'vant';
// import { RadioGroup, Radio } from 'vant';
import { Dialog } from 'vant';
import { AddressList } from 'vant';
import { AddressEdit } from 'vant';
import { Area } from 'vant';



import "vant/lib/button/style";
import "vant/lib/tabbar/style";
import "vant/lib/tabbar-item/style";
import "vant/lib/swipe/style";
import "vant/lib/swipe-item/style";
import "vant/lib/grid/style";
import "vant/lib/grid-item/style";
import "vant/lib/image/style";
import "vant/lib/tab/style";
import "vant/lib/tabs/style";
import "vant/lib/card/style";
import "vant/lib/sidebar/style";
import "vant/lib/sidebar-item/style";
import "vant/lib/list/style";
import "vant/lib/pull-refresh/style";
import "vant/lib/index-bar/style";
import "vant/lib/goods-action/style";
import "vant/lib/goods-action-button/style";
import "vant/lib/goods-action-icon/style";
import "vant/lib/toast/style";
import "vant/lib/checkbox/style";
import "vant/lib/checkbox-group/style";
import "vant/lib/submit-bar/style";
import "vant/lib/stepper/style";
import "vant/lib/form/style";
import "vant/lib/field/style";
// import "vant/lib/sku/style";
// import "vant/lib/overlay/style";
import "vant/lib/popup/style";
import "vant/lib/cell/style";
import "vant/lib/cell-group/style";
// import "vant/lib/col/style";
// import "vant/lib/row/style";
// import "vant/lib/radio/style";
// import "vant/lib/radio-group/style";
import "vant/lib/dialog/style";
import "vant/lib/address-list/style";
import "vant/lib/address-edit/style";
import "vant/lib/area/style";

Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);
Vue.use(Grid);
Vue.use(GridItem);
// Vue.use(Image)
Vue.use(VanImage);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Card);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Toast);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(SubmitBar);
Vue.use(Stepper);
Vue.use(Form);
Vue.use(Field);
// Vue.use(Sku);
// Vue.use(Overlay);
Vue.use(Popup);
Vue.use(Cell);
Vue.use(CellGroup);
// Vue.use(Col);
// Vue.use(Row);
// Vue.use(Radio);
// Vue.use(RadioGroup);
 Vue.use(Dialog);
// Dialog({ message: '提示' });
Vue.use(AddressList);
Vue.use(AddressEdit);
Vue.use(Area)

